version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: [ "--bind=:11900", "--bind-https=:11901" ]
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - se-portainer:/data
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=11900"
      - "traefik.http.routers.portainer.rule=Host(`portainer.salvatoreemilio.it\
        `) || Host(`www.portainer.salvatoreemilio.it`)"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.middlewares=error-middleware"

volumes:
  se-portainer:
    external: true
networks:
  default:
    external: true
    name: se-default
